"""project tags

Revision ID: 180e27266e71
Revises: 773c151f471b
Create Date: 2020-08-20 19:28:37.583317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180e27266e71'
down_revision = '773c151f471b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
