"""added ratings

Revision ID: 573afdab1820
Revises: 180e27266e71
Create Date: 2020-08-20 22:20:50.618074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573afdab1820'
down_revision = '180e27266e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('rater_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###
