"""removed project image

Revision ID: 773c151f471b
Revises: f05a6066fd57
Create Date: 2020-08-19 21:30:27.061213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773c151f471b'
down_revision = 'f05a6066fd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
