"""projects table

Revision ID: 892c31194d66
Revises: c34d49c9f3f1
Create Date: 2020-08-17 21:27:40.331239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892c31194d66'
down_revision = 'c34d49c9f3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=15), nullable=True),
    sa.Column('git_url', sa.String(length=50), nullable=True),
    sa.Column('img_url', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_timestamp'), 'project', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_timestamp'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
